### ISSUE TITLE
Eclipse Luna dark theme is messed up

### ISSUE THREAD

**Issue by VictorLamoine** [guari/eclipse-ui-theme#74] opened 2014-07-02 08:15 UTC
I downloaded Eclipse CDT and deleted my workspace to reset all configuration files.

I switched to the dark theme and restarted Eclipse; the UI doesn't look like expected:
![ugly_eclipse](https://cloud.githubusercontent.com/assets/5566160/3453186/e9314a16-01c0-11e4-8840-f5e2df3b0ef1.png)

Ubuntu 12.04 x64

**Comment by guari** [comment] 2014-07-06 13:37
Duplicate of #73

**Closed as completed by guari** 2014-07-06 13:37 UTC

**Comment by dhiren-hamal** [comment] 2016-12-20 04:44
I also have the same problem. Spring Tools Suite(STS) took ubuntu 16.04 default theme which is basically dark and I really don't like that. I want to use STS default theme, not ubuntu. So is it possible to use STS default theme..no dark theme anymore?
