### ISSUE TITLE
Eclipse dark theme/ moonrise dark theme has issue with palette

### ISSUE THREAD

**Issue by littleCoderVA** [guari/eclipse-ui-theme#75] opened 2014-07-05 21:46 UTC
![image](https://cloud.githubusercontent.com/assets/8077431/3487599/e6743cb0-048c-11e4-950f-485211981940.png)
I used to have this problem when using MoonRise theme for eclipse Kapler under Ubuntu. The palette buttons are black at the beginning, and if I hover my mouse pointer on top they will turn white and won't turn back no matter what I do. I currently have the same issue when using Luna's dark theme/Moonrise under windows. Does anyone know the solution to this?
Thanks a lot!

**Comment by guari** [comment] 2014-07-06 13:27
Duplicate of #59

**Closed as completed** 2014-07-06 13:29 UTC
