### ISSUE TITLE
Theme not appearing

### ISSUE THREAD

**Issue by notes01** [guari/eclipse-ui-theme#17] opened 2013-12-16 02:19 UTC
I have Eclipse 4.2.2 (not sure what exact version), and I'm running a Mac OS X 10.7.5. So, I'm not sure if it's related to the MacOS 10.9 issue.
![screen shot 2013-12-15 at 9 19 19 pm](https://f.cloud.github.com/assets/928789/1751658/823b37fe-65f8-11e3-9446-796b21dab302.png)

**Comment by guari** [comment] 2013-12-16 20:36
yes, it's related to the same issue, since no updates came from Eclipse Bugzilla, I'll upload a a package with the workaround..
Duplicate of #12

**Closed as completed** 2013-12-18 15:43 UTC
Labels: duplicate
